cellIdPreamble: "cell-"
gradientMode: "hue"
cells:
  TT_SSL_smart-reporting.movistar.com.pe:
    dataRef: "TT_SSL_smart-reporting.movistar.com.pe"
    labelElementId: "cell-TT_SSL_smart-reporting.movistar.com.pe_label"
    label:
      separator: "space"
      units: "none"
      decimalPoints: 0
    shapeColor:
      thresholdsRef: "TT_SSL_thresholds"
    labelColor:
      thresholdsRef: "TT_SSL_thresholds"
thresholds:
  TT_SSL_thresholds:
    steps:
      - value: 0
        color: "green"
      - value: 200
        color: "yellow"
      - value: 250
        color: "orange"
      - value: 300
        color: "red"
